### ISSUE TITLE
Intercept only model?

### ISSUE THREAD

**Issue by ailich** [benjaminmisiuk/bulkshift#10]
The default method has the backscatter of the "shift" dataset as a predictor and more complicated models can be created by supplying additional SpatRasters to `preds`. Is it possible to specify a simpler intercept only model? If not, it may be useful to add as that would just look at the difference between target and soft and apply a static dB shift across the entire shift layer which may be appropriate in some scenarios.

**Comment by benjaminmisiuk** [comment]
This is already implemented as one of the [model](https://github.com/benjaminmisiuk/bulkshift/blob/main/R/bulkshift.R#L33
) types. You can use `model='mean'`.
