### ISSUE TITLE
Saving Plots Enhancement

### ISSUE THREAD

**Issue by ailich** [benjaminmisiuk/bulkshift#5]
Thanks for creating this very useful function. I think a minor thing that could make it easier to compare/evaluate models and successively merge several backscatter layers in a loop, would be to add the diagnostic plots to the outputted list structure for easy access. For example:

`dist.plots_object<- plot(plot_grid(cdf.plot, pdf.plot, ncol = 1, align="v", rel_heights = c(1,1)))
#Modified line of code to assign plot to object instead of just going to plot window`
then at the end of the function do 
 ```
if(dist.plots){
            result[["plots"]][["dist.plots"]]<- dist.plots_object} else{
                result[["plots"]][["dist.plots"]]<- NULL}
```

Now simply calling `output$plots$dist.plots` would plot the PDF and CDF for that shift. I'm less familiar with plotrgl(), so I'm not sure exactly how to save those plots to a variable, but if that could be done, it could be saved in the same way and added to be called with `output$plots$err.plot`

**Comment by benjaminmisiuk** [comment]
That's a good suggestion. I've added the argument `save.dist.plots`, which adds the distribution plots to the list output. Another improvement is that the output now contains error statistics for both initial and post-shift, which correspond to the what is seen in the plots.

I've also added the argument `save.err.plots`, which saves the error plots to the list output. Unfortunately, it doesn't seem like there's a straightforward way for saving rgl plots, so I've implemented a workaround. If `save.err.plots=TRUE`, then the 3d plot is simply drawn in the graphics device then saved using `recordPlot()`. This means is that you can call the non-interactive 3d plot from the list output using `output$error_plot`, but not the interactive one. There's no issue with calling 2d plots using `output$error_plot`. Note, though, that saving and loading the plots will probably be slow for large datasets, and you could get memory errors. Plotting in the default window is normally turned off when plotting in the rgl window. You can use the `sample` argument to avoid this.

The functionality is all the same as before if you don't specify `save.err.plots`, except I've changed the plotting defaults to `FALSE`.

Finally, if you'd like to customize your plots or are really going for speed, I recommend turning off plotting and simply setting `save.data=TRUE`, which provides the data frame with the response, predictors, error, and shifted values in `output$data`. I think this is probably the only foolproof way to get the exact plots you want - the plotting I've hard-coded uses these values, and is just what I find most useful for evaluating the bulk shifts.
